### ISSUE TITLE
wp-includes/plugin.php error

### ISSUE THREAD

**Issue by fotan** [uthsc/UTHSC-WPCAS#6]
I am trying to use UTHSC-WPCAS on a blog network for the community college I work for and am having some issues.  After it's installed, the CAS Test link in Dashboard shows good information so I think I have everything installed and configured correctly.  I keep seeing the following error at the bottom of the UTHSC-WPCAS admin screens.

Strict Standards:  call_user_func_array() expects parameter 1 to be a valid callback, non-static method UTHSCWPCAS::wpcas_login_url() should not be called statically in /var/www/laneblogs/docroot/wp-includes/plugin.php on line 235

Am I the only one seeing this?  Hopefully not.

Thanks in advance for any help.  I'm a couple months behind on getting CAS working and like this plugin better than the others.

**Comment by gpspake** [comment]
@fotan Funny timing, I noticed the same error this morning and have added a fix that I'll push out in the next day or so probably. I don't think it should cause any serious issues in the meantime but all I did to fix it was made wpcas_login_url a static method.

**Comment by fotan** [comment]
Thanks, @gpspake.

**Comment by gpspake** [comment]
@fotan I've fixed that issue here but I'll still need to push it up to the WP repo... If you want you can go ahead and try it out and see if that resolves the error for you.

**Comment by fotan** [comment]
Thanks @gpspake.  That fixed that problem.  Now I need to track down some issues we have with our specific CAS server, I think.  

I appreciate the quick help.

**Comment by gpspake** [comment]
sure, good luck
